searchSpace:
   n_neurons: 
      _type: choice
      _value: [50, 100, 200, 500, 1000, 2000, 5000] 
   sparsity:
      _type: choice
      _value: [0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99]
   seed:
      _type: choice
      _value: [362,337,504,428,351,305,824,281,324,538,386,313,896,553,706,557,363,727,423,993]
      
experimentName: EXPERIMENT
trialCommand: python exp.py
trialConcurrency: 4
maxTrialNumber: 8000
maxExperimentDuration: 24h
tuner:
   name: GridSearch
trainingService:
   platform: local